export const GET_DIJKSTRA_REQUEST = "GET_DIJKSTRA_REQUEST";
export const GET_DIJKSTRA_SUCCESS = "GET_DIJKSTRA_SUCCESS";
export const GET_DIJKSTRA_FAILED = "GET_DIJKSTRA_FAILED";

export const EXIT_PATH_PREVIEW = "EXIT_PATH_PREVIEW";
