export const SWITCH_THEME_REQUEST = "SWITCH_THEME_REQUEST";
export const SWITCH_THEME_SUCCESS = "SWITCH_THEME_SUCCESS";
export const SWITCH_THEME_FAILED = "SWITCH_THEME_FAILED";

export const SWITCH_LANG_REQUEST = "SWITCH_LANG_REQUEST";
export const SWITCH_LANG_SUCCESS = "SWITCH_LANG_SUCCESS";
export const SWITCH_LANG_FAILED = "SWITCH_LANG_FAILED";
