export const INIT_GRAPH_REQUEST = "INIT_GRAPH_REQUEST";
export const INIT_GRAPH_SUCCESS = "INIT_GRAPH_SUCCESS";
export const INIT_GRAPH_FAILED = "INIT_GRAPH_FAILED";

export const GET_DIJKSTRA_REQUEST = "GET_DIJKSTRA_REQUEST";
export const GET_DIJKSTRA_SUCCESS = "GET_DIJKSTRA_SUCCESS";
export const GET_DIJKSTRA_FAILED = "GET_DIJKSTRA_FAILED";
