export const INIT_GRAPH_REQUEST = "INIT_GRAPH_REQUEST";
export const INIT_GRAPH_SUCCESS = "INIT_GRAPH_SUCCESS";
export const INIT_GRAPH_FAILED = "INIT_GRAPH_FAILED";

export const SET_START_VERTEX = "SET_START_VERTEX";
