export default {
  categories: [
    {
      id: 1,
      name: "alcohol",
    },
    {
      id: 2,
      name: "bakery products",
    },
    {
      id: 3,
      name: "groceries",
    },
    {
      id: 4,
      name: "teas and coffees",
    },
    {
      id: 5,
      name: "sweets",
    },
    {
      id: 6,
      name: "mineral water",
    },
    {
      id: 7,
      name: "beverages and juices",
    },
    {
      id: 8,
      name: "meat and cold cuts",
    },
    {
      id: 9,
      name: "cheeses",
    },
    {
      id: 10,
      name: "frozen foods",
    },
    {
      id: 11,
      name: "savoury snacks",
    },
    {
      id: 12,
      name: "fishes",
    },
    {
      id: 13,
      name: "honey and dried fruits",
    },
    {
      id: 14,
      name: "eggs",
    },
    {
      id: 15,
      name: "delicatessen",
    },
    {
      id: 16,
      name: "spices",
    },
    {
      id: 17,
      name: "preserves",
    },
    {
      id: 18,
      name: "ready meals",
    },
    {
      id: 19,
      name: "cleaning products",
    },
    {
      id: 20,
      name: "animal world",
    },
    {
      id: 21,
      name: "ice creams",
    },
    {
      id: 22,
      name: "dairy products",
    },
    {
      id: 23,
      name: "deals",
    },
    {
      id: 24,
      name: "checkout",
    },
    {
      id: 25,
      name: "fruits and vegetables",
    },
  ],
  products: [
    {
      id: 1,
      name: "Guinness Draught",
      desc: "-",
      price: "2.50",
      objectId: "o_5",
    },
    {
      id: 2,
      name: "Orange juice",
      desc: "-",
      price: "2.50",
      objectId: "o_10",
    },
    {
      id: 3,
      name: "Milk",
      desc: "-",
      price: "2.50",
      objectId: "o_8",
    },
    {
      id: 4,
      name: "Chocolate",
      desc: "-",
      price: "2.50",
      objectId: "o_25",
    },
    {
      id: 5,
      name: "Salmon",
      desc: "-",
      price: "2.50",
      objectId: "o_21",
    },
    {
      id: 6,
      name: "Pasta",
      desc: "-",
      price: "2.50",
      objectId: "o_35",
    },
    {
      id: 7,
      name: "Eggs",
      desc: "-",
      price: "2.50",
      objectId: "o_18",
    },
    {
      id: 8,
      name: "Heineken",
      desc: "-",
      price: "2.50",
      objectId: "o_11",
    },
    {
      id: 9,
      name: "Corona Extra",
      desc: "-",
      price: "2.50",
      objectId: "o_11",
    },
    {
      id: 10,
      name: "Punk IPA",
      desc: "-",
      price: "2.50",
      objectId: "o_1",
    },
    {
      id: 11,
      name: "Bud Light",
      desc: "-",
      price: "2.50",
      objectId: "o_5",
    },
    {
      id: 12,
      name: "Traditional Lager",
      desc: "-",
      price: "2.50",
      objectId: "o_5",
    },
    {
      id: 13,
      name: "Lay's salted",
      desc: "-",
      price: "5.99",
      objectId: "o_28",
    },
    {
      id: 14,
      name: "Pepper",
      desc: "-",
      price: "2.00",
      objectId: "o_15",
    },
    {
      id: 15,
      name: "Pierogi",
      desc: "True Polish OG food",
      price: "9.99",
      objectId: "o_24",
    },
    {
      id: 16,
      name: "Instant soup",
      desc: "-",
      price: "2.50",
      objectId: "o_14",
    },
    {
      id: 17,
      name: "Salt",
      desc: "-",
      price: "1.00",
      objectId: "o_16",
    },
    {
      id: 18,
      name: "Coffee",
      desc: "-",
      price: "15.00",
      objectId: "o_33",
    },
    {
      id: 19,
      name: "Black tea",
      desc: "-",
      price: "1.00",
      objectId: "o_32",
    },
    {
      id: 20,
      name: "Green tea",
      desc: "-",
      price: "1.00",
      objectId: "o_32",
    },
    {
      id: 21,
      name: "Tomatoes",
      desc: "-",
      price: "2.00",
      objectId: "o_34",
    },
    {
      id: 22,
      name: "Bananas",
      desc: "-",
      price: "4.99",
      objectId: "o_30",
    },
    {
      id: 23,
      name: "Apples",
      desc: "-",
      price: "3.99",
      objectId: "o_30",
    },
    {
      id: 24,
      name: "Salty sticks",
      desc: "-",
      price: "3.99",
      objectId: "o_28",
    },
    {
      id: 25,
      name: "Cream tubes",
      desc: "-",
      price: "4.50",
      objectId: "o_26",
    },
    {
      id: 26,
      name: "Waffles",
      desc: "-",
      price: "4.50",
      objectId: "o_27",
    },
    {
      id: 27,
      name: "American cookies",
      desc: "-",
      price: "4.39",
      objectId: "o_25",
    },
    {
      id: 28,
      name: "Bread",
      desc: "-",
      price: "3.00",
      objectId: "o_38",
    },
    {
      id: 29,
      name: "Roll",
      desc: "-",
      price: "3.29",
      objectId: "o_43",
    },
    {
      id: 30,
      name: "Corn",
      desc: "-",
      price: "2.40",
      objectId: "o_36",
    },
    {
      id: 31,
      name: "Tomato sauce",
      desc: "-",
      price: "5.19",
      objectId: "o_37",
    },
    {
      id: 32,
      name: "Gouda cheese",
      desc: "-",
      price: "5.19",
      objectId: "o_13",
    },
    {
      id: 33,
      name: "Blue cheese",
      desc: "-",
      price: "6.00",
      objectId: "o_39",
    },
    {
      id: 34,
      name: "Ham",
      desc: "-",
      price: "5.00",
      objectId: "o_42",
    },
    {
      id: 35,
      name: "Salami",
      desc: "-",
      price: "3.00",
      objectId: "o_41",
    },
    {
      id: 36,
      name: "Peanuts",
      desc: "-",
      price: "6.00",
      objectId: "o_22",
    },
    {
      id: 37,
      name: "Honey",
      desc: "-",
      price: "20.00",
      objectId: "o_22",
    },
    {
      id: 38,
      name: "Jam",
      desc: "-",
      price: "7.00",
      objectId: "o_23",
    },
    {
      id: 39,
      name: "Detergent",
      desc: "-",
      price: "25.00",
      objectId: "o_31",
    },
    {
      id: 40,
      name: "karma dla psa",
      desc: "-",
      price: "30.00",
      objectId: "o_29",
    },
    {
      id: 41,
      name: "Ice cream",
      desc: "-",
      price: "2.89",
      objectId: "o_20",
    },
    {
      id: 42,
      name: "Frozen vegetables",
      desc: "-",
      price: "12.00",
      objectId: "o_17",
    },
    {
      id: 43,
      name: "Candy box",
      desc: "-",
      price: "5.00",
      objectId: "o_19",
    },
    {
      id: 44,
      name: "Natural yogurt",
      desc: "-",
      price: "3.00",
      objectId: "o_7",
    },
    {
      id: 45,
      name: "Cottage cheese",
      desc: "-",
      price: "3.00",
      objectId: "o_2",
    },
    {
      id: 46,
      name: "Sparkling water",
      desc: "-",
      price: "1.79",
      objectId: "o_4",
    },
    {
      id: 47,
      name: "Mineral water",
      desc: "-",
      price: "2.79",
      objectId: "o_9",
    },
    {
      id: 48,
      name: "Cola",
      desc: "-",
      price: "4.79",
      objectId: "o_6",
    },
    {
      id: 49,
      name: "Orange soda",
      desc: "-",
      price: "4.79",
      objectId: "o_3",
    },
    {
      id: 50,
      name: "Vodka",
      desc: "-",
      price: "25.00",
      objectId: "o_12",
    },
    {
      id: 51,
      name: "Chewing gums",
      desc: "-",
      price: "3.00",
      objectId: "o_40",
    },
  ],
  "object-to-category": [
    {
      id: 1,
      categoryId: 1,
      objectId: "o_1",
    },
    {
      id: 2,
      categoryId: 22,
      objectId: "o_2",
    },
    {
      id: 3,
      categoryId: 7,
      objectId: "o_3",
    },
    {
      id: 4,
      categoryId: 6,
      objectId: "o_4",
    },
    {
      id: 5,
      categoryId: 1,
      objectId: "o_5",
    },
    {
      id: 6,
      categoryId: 7,
      objectId: "o_6",
    },
    {
      id: 7,
      categoryId: 22,
      objectId: "o_7",
    },
    {
      id: 8,
      categoryId: 22,
      objectId: "o_8",
    },
    {
      id: 9,
      categoryId: 6,
      objectId: "o_9",
    },
    {
      id: 10,
      categoryId: 7,
      objectId: "o_10",
    },
    {
      id: 11,
      categoryId: 1,
      objectId: "o_11",
    },
    {
      id: 12,
      categoryId: 1,
      objectId: "o_12",
    },
    {
      id: 13,
      categoryId: 9,
      objectId: "o_13",
    },
    {
      id: 14,
      categoryId: 18,
      objectId: "o_14",
    },
    {
      id: 15,
      categoryId: 16,
      objectId: "o_15",
    },
    {
      id: 16,
      categoryId: 16,
      objectId: "o_16",
    },
    {
      id: 17,
      categoryId: 10,
      objectId: "o_17",
    },
    {
      id: 18,
      categoryId: 14,
      objectId: "o_18",
    },
    {
      id: 19,
      categoryId: 23,
      objectId: "o_19",
    },
    {
      id: 20,
      categoryId: 21,
      objectId: "o_20",
    },
    {
      id: 21,
      categoryId: 12,
      objectId: "o_21",
    },
    {
      id: 22,
      categoryId: 13,
      objectId: "o_22",
    },
    {
      id: 23,
      categoryId: 17,
      objectId: "o_23",
    },
    {
      id: 24,
      categoryId: 15,
      objectId: "o_24",
    },
    {
      id: 25,
      categoryId: 5,
      objectId: "o_25",
    },
    {
      id: 26,
      categoryId: 5,
      objectId: "o_26",
    },
    {
      id: 27,
      categoryId: 5,
      objectId: "o_27",
    },
    {
      id: 28,
      categoryId: 11,
      objectId: "o_28",
    },
    {
      id: 29,
      categoryId: 20,
      objectId: "o_29",
    },
    {
      id: 30,
      categoryId: 25,
      objectId: "o_30",
    },
    {
      id: 31,
      categoryId: 19,
      objectId: "o_31",
    },
    {
      id: 32,
      categoryId: 4,
      objectId: "o_32",
    },
    {
      id: 33,
      categoryId: 4,
      objectId: "o_33",
    },
    {
      id: 34,
      categoryId: 25,
      objectId: "o_34",
    },
    {
      id: 35,
      categoryId: 3,
      objectId: "o_35",
    },
    {
      id: 36,
      categoryId: 3,
      objectId: "o_36",
    },
    {
      id: 37,
      categoryId: 3,
      objectId: "o_37",
    },
    {
      id: 38,
      categoryId: 2,
      objectId: "o_38",
    },
    {
      id: 39,
      categoryId: 9,
      objectId: "o_39",
    },
    {
      id: 40,
      categoryId: 24,
      objectId: "o_40",
    },
    {
      id: 41,
      categoryId: 8,
      objectId: "o_41",
    },
    {
      id: 42,
      categoryId: 8,
      objectId: "o_42",
    },
    {
      id: 43,
      categoryId: 2,
      objectId: "o_43",
    },
  ],
};
