import * as React from "react";
import classNames from "classnames";

import styles from "./Map.module.scss";

function SvgComponent(props: any) {
  const { mapData: m }: any = props;
  const { vertexRefCallback }: any = props;
  const { edgeRefCallback }: any = props;

  console.log(styles);

  return (
    <svg
      width={1113}
      height={773}
      viewBox="0 0 1113 773"
      fill="none"
      {...props}
    >
      <g id="prefix__Map">
        <g id="prefix__floor" filter="url(#prefix__filter0_d)">
          <path d="M1057.5 55H55v663h715l287.5-220.5V55z" fill="#fff" />
          <path
            d="M1057.5 55H55v663h715l287.5-220.5V55z"
            stroke="#F8F8F8"
            strokeWidth={10}
          />
        </g>
        <g id="prefix__Edges" fill="#000">
          <rect
            id="prefix__e_107"
            x={109}
            y={230}
            width={1}
            height={157}
            rx={0.5}
            data-edge-keys={m.e.v_96__v_79.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_106"
            x={109}
            y={105}
            width={1}
            height={126}
            rx={0.5}
            data-edge-keys={m.e.v_79__v_75.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_105"
            x={240}
            y={105}
            width={1}
            height={135}
            rx={0.5}
            data-edge-keys={m.e.v_69__v_67.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_104"
            x={316}
            y={105}
            width={1}
            height={65}
            rx={0.5}
            data-edge-keys={m.e.v_72__v_71.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_103"
            x={421}
            y={201}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_102"
            x={525}
            y={201}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_101"
            x={525}
            y={239}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_100"
            x={463}
            y={105}
            width={1}
            height={65}
            rx={0.5}
            data-edge-keys={m.e.v_74__v_70.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_99"
            x={463}
            y={66}
            width={1}
            height={40}
            rx={0.5}
            data-edge-keys={m.e.v_74__v_73.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_98"
            x={711}
            y={66}
            width={1}
            height={40}
            rx={0.5}
            data-edge-keys={m.e.v_15__v_14.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_97"
            x={785}
            y={201}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_96"
            x={838}
            y={239}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_95"
            x={890}
            y={309}
            width={1}
            height={41}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_94"
            x={890}
            y={349}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_93"
            x={838}
            y={105}
            width={1}
            height={65}
            rx={0.5}
            data-edge-keys={m.e.v_13__v_12.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_92"
            x={240}
            y={66}
            width={1}
            height={40}
            rx={0.5}
            data-edge-keys={m.e.v_69__v_68.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_91"
            x={600}
            y={105}
            width={1}
            height={135}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_90"
            x={600}
            y={239}
            width={1}
            height={106}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_89"
            x={600}
            y={344}
            width={1}
            height={43}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_88"
            x={600}
            y={386}
            width={1}
            height={38}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_87"
            x={600}
            y={423}
            width={1}
            height={108}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_86"
            x={600}
            y={530}
            width={1}
            height={133}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_85"
            x={711}
            y={565}
            width={1}
            height={98}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_84"
            x={711}
            y={460}
            width={1}
            height={106}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_83"
            x={760}
            y={529}
            width={1}
            height={37}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_82"
            x={785}
            y={460}
            width={1}
            height={38}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_81"
            x={785}
            y={419}
            width={1}
            height={42}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_80"
            x={890}
            y={419}
            width={1}
            height={42}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_79"
            x={711}
            y={386}
            width={1}
            height={75}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_78"
            x={711}
            y={349}
            width={1}
            height={38}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_77"
            x={711}
            y={239}
            width={1}
            height={111}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_76"
            x={990}
            y={239}
            width={1}
            height={111}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_75"
            x={990}
            y={349}
            width={1}
            height={55}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_74"
            x={990}
            y={403}
            width={1}
            height={58}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_73"
            x={711}
            y={105}
            width={1}
            height={135}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_72"
            x={990}
            y={105}
            width={1}
            height={135}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_71"
            x={240}
            y={239}
            width={1}
            height={106}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_70"
            x={421}
            y={309}
            width={1}
            height={36}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_69"
            x={475}
            y={344}
            width={1}
            height={43}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_68"
            x={473}
            y={423}
            width={1}
            height={38}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_67"
            x={316}
            y={239}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_66"
            x={316}
            y={309}
            width={1}
            height={36}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_65"
            x={240}
            y={344}
            width={1}
            height={43}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_64"
            x={240}
            y={386}
            width={1}
            height={38}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_63"
            x={240}
            y={423}
            width={1}
            height={38}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_62"
            x={240}
            y={460}
            width={1}
            height={71}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_61"
            x={240}
            y={530}
            width={1}
            height={133}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_60"
            x={240}
            y={662}
            width={1}
            height={45}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_59"
            x={316}
            y={600}
            width={1}
            height={63}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_58"
            x={473}
            y={600}
            width={1}
            height={63}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_57"
            x={473}
            y={662}
            width={1}
            height={45}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_56"
            x={368}
            y={530}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_55"
            x={525}
            y={492}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_54"
            x={368}
            y={492}
            width={1}
            height={39}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_53"
            x={109}
            y={534}
            width={1}
            height={129}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_52"
            x={109}
            y={662}
            width={1}
            height={45}
            rx={0.5}
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_51"
            x={109}
            y={386}
            width={1}
            height={149}
            rx={0.5}
            data-edge-keys={m.e.v_96__v_94.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_50"
            x={241}
            y={105}
            width={1}
            height={132}
            rx={0.5}
            transform="rotate(90 241 105)"
            data-edge-keys={m.e.v_75__v_69.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_49"
            x={110}
            y={105}
            width={1}
            height={44}
            rx={0.5}
            transform="rotate(90 110 105)"
            data-edge-keys={m.e.v_75__v_76.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_48"
            x={241}
            y={386}
            width={1}
            height={132}
            rx={0.5}
            transform="rotate(90 241 386)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_47"
            x={241}
            y={460}
            width={1}
            height={39}
            rx={0.5}
            transform="rotate(90 241 460)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_46"
            x={171}
            y={534}
            width={1}
            height={62}
            rx={0.5}
            transform="rotate(90 171 534)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_45"
            x={110}
            y={534}
            width={1}
            height={44}
            rx={0.5}
            transform="rotate(90 110 534)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_44"
            x={110}
            y={386}
            width={1}
            height={35}
            rx={0.5}
            transform="rotate(90 110 386)"
            data-edge-keys={m.e.v_95__v_96.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_43"
            x={317.001}
            y={344}
            width={1}
            height={77}
            rx={0.5}
            transform="rotate(90 317.001 344)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_42"
            x={317.001}
            y={239}
            width={1}
            height={77}
            rx={0.5}
            transform="rotate(90 317.001 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_41"
            x={186}
            y={230}
            width={1}
            height={77}
            rx={0.5}
            transform="rotate(90 186 230)"
            data-edge-keys={m.e.v_79__v_78.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_40"
            x={110}
            y={230}
            width={1}
            height={44}
            rx={0.5}
            transform="rotate(90 110 230)"
            data-edge-keys={m.e.v_79__v_77.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_39"
            x={422.001}
            y={239}
            width={1}
            height={106}
            rx={0.5}
            transform="rotate(90 422.001 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_38"
            x={526.001}
            y={239}
            width={1}
            height={105}
            rx={0.5}
            transform="rotate(90 526.001 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_37"
            x={601}
            y={239}
            width={1}
            height={76}
            rx={0.5}
            transform="rotate(90 601 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_36"
            x={640}
            y={239}
            width={1}
            height={40}
            rx={0.5}
            transform="rotate(90 640 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_35"
            x={712}
            y={239}
            width={1}
            height={41}
            rx={0.5}
            transform="rotate(90 712 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_34"
            x={422}
            y={344}
            width={1}
            height={106}
            rx={0.5}
            transform="rotate(90 422 344)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_33"
            x={476}
            y={344}
            width={1}
            height={55}
            rx={0.5}
            transform="rotate(90 476 344)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_32"
            x={601}
            y={344}
            width={1}
            height={126}
            rx={0.5}
            transform="rotate(90 601 344)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_31"
            x={601}
            y={423}
            width={1}
            height={128}
            rx={0.5}
            transform="rotate(90 601 423)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_30"
            x={601}
            y={530}
            width={1}
            height={76}
            rx={0.5}
            transform="rotate(90 601 530)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_29"
            x={640}
            y={530}
            width={1}
            height={40}
            rx={0.5}
            transform="rotate(90 640 530)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_28"
            x={526}
            y={530}
            width={1}
            height={158}
            rx={0.5}
            transform="rotate(90 526 530)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_27"
            x={369.007}
            y={530}
            width={1}
            height={129}
            rx={0.5}
            transform="rotate(90 369.007 530)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_26"
            x={317.007}
            y={662}
            width={1}
            height={77}
            rx={0.5}
            transform="rotate(90 317.007 662)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <g id="prefix__e_25">
            <path
              d="M394.749 662v1H316.5a.5.5 0 010-1h78.249zM473.5 662a.5.5 0 010 1h-78.751v-1H473.5z"
              data-edge-keys={m.e.v_1__v_2.key}
              ref={edgeRefCallback}
              className={classNames(styles["Edge"])}
            />
          </g>
          <g id="prefix__e_24">
            <path
              d="M536.799 662v1h-63.297a.5.5 0 010-1h63.297zM600.502 662a.5.5 0 110 1h-63.703v-1h63.703z"
              data-edge-keys={m.e.v_1__v_2.key}
              ref={edgeRefCallback}
              className={classNames(styles["Edge"])}
            />
          </g>
          <g id="prefix__e_23">
            <path
              d="M655.822 662v1H600.5a.5.5 0 010-1h55.322zM711.5 662a.5.5 0 010 1h-55.678v-1H711.5z"
              data-edge-keys={m.e.v_1__v_2.key}
              ref={edgeRefCallback}
              className={classNames(styles["Edge"])}
            />
          </g>
          <rect
            id="prefix__e_22"
            x={241.007}
            y={662}
            width={1}
            height={132}
            rx={0.5}
            transform="rotate(90 241.007 662)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_21"
            x={474}
            y={423}
            width={1}
            height={234}
            rx={0.5}
            transform="rotate(90 474 423)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_20"
            x={317}
            y={105}
            width={1}
            height={77}
            rx={0.5}
            transform="rotate(90 317 105)"
            data-edge-keys={m.e.v_69__v_72.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_19"
            x={464}
            y={105}
            width={1}
            height={148}
            rx={0.5}
            transform="rotate(90 464 105)"
            data-edge-keys={m.e.v_72__v_74.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_18"
            x={601}
            y={105}
            width={1}
            height={138}
            rx={0.5}
            transform="rotate(90 601 105)"
            data-edge-keys={m.e.v_74__v_21.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_17"
            x={712.003}
            y={105}
            width={1}
            height={112}
            rx={0.5}
            transform="rotate(90 712.003 105)"
            data-edge-keys={m.e.v_21__v_15.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_16"
            x={786.002}
            y={239}
            width={1}
            height={75}
            rx={0.5}
            transform="rotate(90 786.002 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_15"
            x={839.001}
            y={239}
            width={1}
            height={54}
            rx={0.5}
            transform="rotate(90 839.001 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_14"
            x={991}
            y={239}
            width={1}
            height={153}
            rx={0.5}
            transform="rotate(90 991 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_13"
            x={991}
            y={349}
            width={1}
            height={101}
            rx={0.5}
            transform="rotate(90 991 349)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_12"
            x={1046}
            y={403}
            width={1}
            height={56}
            rx={0.5}
            transform="rotate(90 1046 403)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_11"
            x={891}
            y={349}
            width={1}
            height={180}
            rx={0.5}
            transform="rotate(90 891 349)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_10"
            x={786}
            y={460}
            width={1}
            height={75}
            rx={0.5}
            transform="rotate(90 786 460)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_9"
            x={761}
            y={565}
            width={1}
            height={50}
            rx={0.5}
            transform="rotate(90 761 565)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_8"
            x={712}
            y={565}
            width={1}
            height={41}
            rx={0.5}
            transform="rotate(90 712 565)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_7"
            x={891}
            y={460}
            width={1}
            height={106}
            rx={0.5}
            transform="rotate(90 891 460)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_6"
            x={991}
            y={460}
            width={1}
            height={101}
            rx={0.5}
            transform="rotate(90 991 460)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_5"
            x={712}
            y={386}
            width={1}
            height={112}
            rx={0.5}
            transform="rotate(90 712 386)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_4"
            x={839}
            y={105}
            width={1}
            height={128}
            rx={0.5}
            transform="rotate(90 839 105)"
            data-edge-keys={m.e.v_15__v_13.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_3"
            x={991}
            y={105}
            width={1}
            height={153}
            rx={0.5}
            transform="rotate(90 991 105)"
            data-edge-keys={m.e.v_13__v_11.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_2"
            x={1046}
            y={105}
            width={1}
            height={56}
            rx={0.5}
            transform="rotate(90 1046 105)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
          <rect
            id="prefix__e_1"
            x={1046}
            y={239}
            width={1}
            height={56}
            rx={0.5}
            transform="rotate(90 1046 239)"
            data-edge-keys={m.e.v_1__v_2.key}
            ref={edgeRefCallback}
            className={classNames(styles["Edge"])}
          />
        </g>
        <g id="prefix__Vertices">
          <circle
            id="prefix__v_96"
            cx={109.5}
            cy={386.5}
            r={4.5}
            data-vertex-key={m.v.v_96.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_95"
            cx={75.5}
            cy={386.5}
            r={4.5}
            data-vertex-key={m.v.v_95.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_94"
            cx={109.5}
            cy={534.5}
            r={4.5}
            data-vertex-key={m.v.v_94.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_93"
            cx={66.5}
            cy={534.5}
            r={4.5}
            data-vertex-key={m.v.v_93.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_92"
            cx={170.5}
            cy={534.5}
            r={4.5}
            data-vertex-key={m.v.v_92.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_91"
            cx={109.5}
            cy={662.5}
            r={4.5}
            data-vertex-key={m.v.v_91.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_90"
            cx={109.5}
            cy={706.5}
            r={4.5}
            data-vertex-key={m.v.v_90.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_89"
            cx={240.5}
            cy={662.5}
            r={4.5}
            data-vertex-key={m.v.v_89.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_88"
            cx={240.5}
            cy={706.5}
            r={4.5}
            data-vertex-key={m.v.v_88.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_87"
            cx={473.5}
            cy={706.5}
            r={4.5}
            data-vertex-key={m.v.v_87.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_86"
            cx={316.5}
            cy={662.5}
            r={4.5}
            data-vertex-key={m.v.v_86.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_85"
            cx={316.5}
            cy={600.5}
            r={4.5}
            data-vertex-key={m.v.v_85.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_84"
            cx={473.5}
            cy={662.5}
            r={4.5}
            data-vertex-key={m.v.v_84.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_83"
            cx={473.5}
            cy={600.5}
            r={4.5}
            data-vertex-key={m.v.v_83.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_82"
            cx={600.5}
            cy={662.5}
            r={4.5}
            data-vertex-key={m.v.v_82.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_81"
            cx={600.5}
            cy={530.5}
            r={4.5}
            data-vertex-key={m.v.v_81.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_80"
            cx={639.5}
            cy={530.5}
            r={4.5}
            data-vertex-key={m.v.v_80.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_79"
            cx={109.5}
            cy={230.5}
            r={4.5}
            data-vertex-key={m.v.v_79.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_78"
            cx={185.5}
            cy={230.5}
            r={4.5}
            data-vertex-key={m.v.v_78.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_77"
            cx={66.5}
            cy={230.5}
            r={4.5}
            data-vertex-key={m.v.v_77.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_76"
            cx={66.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_76.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_75"
            cx={109.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_75.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_74"
            cx={463.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_74.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_73"
            cx={463.5}
            cy={66.5}
            r={4.5}
            data-vertex-key={m.v.v_73.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_72"
            cx={316.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_72.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_71"
            cx={316.5}
            cy={169.5}
            r={4.5}
            data-vertex-key={m.v.v_71.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_70"
            cx={463.5}
            cy={169.5}
            r={4.5}
            data-vertex-key={m.v.v_70.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_69"
            cx={240.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_69.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_68"
            cx={240.5}
            cy={66.5}
            r={4.5}
            data-vertex-key={m.v.v_68.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_67"
            cx={240.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_67.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_66"
            cx={240.5}
            cy={344.5}
            r={4.5}
            data-vertex-key={m.v.v_66.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_65"
            cx={240.5}
            cy={386.5}
            r={4.5}
            data-vertex-key={m.v.v_65.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_64"
            cx={240.5}
            cy={460.5}
            r={4.5}
            data-vertex-key={m.v.v_64.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_63"
            cx={202.5}
            cy={460.5}
            r={4.5}
            data-vertex-key={m.v.v_63.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_62"
            cx={240.5}
            cy={530.5}
            r={4.5}
            data-vertex-key={m.v.v_62.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_61"
            cx={368.5}
            cy={530.5}
            r={4.5}
            data-vertex-key={m.v.v_61.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_60"
            cx={368.5}
            cy={492.5}
            r={4.5}
            data-vertex-key={m.v.v_60.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_59"
            cx={368.5}
            cy={568.5}
            r={4.5}
            data-vertex-key={m.v.v_59.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_58"
            cx={525.5}
            cy={530.5}
            r={4.5}
            data-vertex-key={m.v.v_58.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_57"
            cx={525.5}
            cy={492.5}
            r={4.5}
            data-vertex-key={m.v.v_57.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_56"
            cx={240.5}
            cy={423.5}
            r={4.5}
            data-vertex-key={m.v.v_56.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_55"
            cx={473.5}
            cy={423.5}
            r={4.5}
            data-vertex-key={m.v.v_55.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_54"
            cx={473.5}
            cy={460.5}
            r={4.5}
            data-vertex-key={m.v.v_54.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_53"
            cx={600.5}
            cy={423.5}
            r={4.5}
            data-vertex-key={m.v.v_53.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_52"
            cx={316.5}
            cy={344.5}
            r={4.5}
            data-vertex-key={m.v.v_52.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_51"
            cx={421.5}
            cy={344.5}
            r={4.5}
            data-vertex-key={m.v.v_51.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_50"
            cx={421.5}
            cy={309.5}
            r={4.5}
            data-vertex-key={m.v.v_50.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_49"
            cx={316.5}
            cy={309.5}
            r={4.5}
            data-vertex-key={m.v.v_49.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_48"
            cx={316.5}
            cy={277.5}
            r={4.5}
            data-vertex-key={m.v.v_48.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_47"
            cx={475.5}
            cy={344.5}
            r={4.5}
            data-vertex-key={m.v.v_47.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_46"
            cx={475.5}
            cy={386.5}
            r={4.5}
            data-vertex-key={m.v.v_46.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_45"
            cx={600.5}
            cy={344.5}
            r={4.5}
            data-vertex-key={m.v.v_45.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_44"
            cx={600.5}
            cy={386.5}
            r={4.5}
            data-vertex-key={m.v.v_44.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_43"
            cx={711.5}
            cy={386.5}
            r={4.5}
            data-vertex-key={m.v.v_43.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_42"
            cx={711.5}
            cy={460.5}
            r={4.5}
            data-vertex-key={m.v.v_42.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_41"
            cx={785.5}
            cy={460.5}
            r={4.5}
            data-vertex-key={m.v.v_41.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_40"
            cx={785.5}
            cy={497.5}
            r={4.5}
            data-vertex-key={m.v.v_40.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_39"
            cx={785.5}
            cy={419.5}
            r={4.5}
            data-vertex-key={m.v.v_39.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_38"
            cx={890.5}
            cy={460.5}
            r={4.5}
            data-vertex-key={m.v.v_38.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_37"
            cx={890.5}
            cy={419.5}
            r={4.5}
            data-vertex-key={m.v.v_37.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_36"
            cx={711.5}
            cy={565.5}
            r={4.5}
            data-vertex-key={m.v.v_36.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_35"
            cx={671.5}
            cy={565.5}
            r={4.5}
            data-vertex-key={m.v.v_35.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_34"
            cx={711.5}
            cy={662.5}
            r={4.5}
            data-vertex-key={m.v.v_34.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_33"
            cx={760.5}
            cy={565.5}
            r={4.5}
            data-vertex-key={m.v.v_33.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_32"
            cx={760.5}
            cy={529.5}
            r={4.5}
            data-vertex-key={m.v.v_32.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <path
            id="prefix__v_31"
            d="M995 460.5a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0z"
            data-vertex-key={m.v.v_31.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_30"
            cx={316.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_30.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_29"
            r={4.5}
            transform="matrix(1 0 0 -1 421.5 239.5)"
            data-vertex-key={m.v.v_29.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_28"
            r={4.5}
            transform="matrix(1 0 0 -1 421.5 201.5)"
            data-vertex-key={m.v.v_28.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_27"
            r={4.5}
            transform="matrix(1 0 0 -1 525.5 201.5)"
            data-vertex-key={m.v.v_27.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_26"
            r={4.5}
            transform="matrix(1 0 0 -1 525.5 239.5)"
            data-vertex-key={m.v.v_26.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_25"
            r={4.5}
            transform="matrix(1 0 0 -1 525.5 277.5)"
            data-vertex-key={m.v.v_25.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_24"
            r={4.5}
            transform="matrix(1 0 0 -1 600.5 239.5)"
            data-vertex-key={m.v.v_24.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_23"
            r={4.5}
            transform="matrix(1 0 0 -1 639.5 239.5)"
            data-vertex-key={m.v.v_23.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_22"
            r={4.5}
            transform="matrix(1 0 0 -1 671.5 239.5)"
            data-vertex-key={m.v.v_22.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_21"
            r={4.5}
            transform="matrix(1 0 0 -1 600.5 105.5)"
            data-vertex-key={m.v.v_21.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_20"
            cx={711.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_20.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_19"
            cx={785.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_19.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_18"
            cx={785.5}
            cy={201.5}
            r={4.5}
            data-vertex-key={m.v.v_18.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_17"
            cx={838.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_17.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_16"
            cx={838.5}
            cy={277.5}
            r={4.5}
            data-vertex-key={m.v.v_16.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_15"
            cx={711.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_15.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_14"
            cx={711.5}
            cy={66.5}
            r={4.5}
            data-vertex-key={m.v.v_14.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_13"
            cx={838.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_13.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_12"
            cx={838.5}
            cy={169.5}
            r={4.5}
            data-vertex-key={m.v.v_12.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_11"
            cx={990.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_11.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_10"
            cx={1045.5}
            cy={105.5}
            r={4.5}
            data-vertex-key={m.v.v_10.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_9"
            cx={1045.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_9.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_8"
            cx={990.5}
            cy={239.5}
            r={4.5}
            data-vertex-key={m.v.v_8.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_7"
            cx={990.5}
            cy={403.5}
            r={4.5}
            data-vertex-key={m.v.v_7.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_6"
            cx={1045.5}
            cy={403.5}
            r={4.5}
            data-vertex-key={m.v.v_6.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_5"
            cx={990.5}
            cy={349.5}
            r={4.5}
            data-vertex-key={m.v.v_5.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_4"
            cx={890.5}
            cy={349.5}
            r={4.5}
            data-vertex-key={m.v.v_4.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_3"
            cx={890.5}
            cy={309.5}
            r={4.5}
            data-vertex-key={m.v.v_3.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_2"
            cx={890.5}
            cy={387.5}
            r={4.5}
            data-vertex-key={m.v.v_2.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
          <circle
            id="prefix__v_1"
            cx={711.5}
            cy={349.5}
            r={4.5}
            data-vertex-key={m.v.v_1.key}
            ref={vertexRefCallback}
            className={classNames(styles["Vertex"])}
          />
        </g>
        <g id="prefix__Objects">
          <path
            id="prefix__o_43"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M156.5 411.5h27v204h-27z"
          />
          <path
            id="prefix__o_42"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M626.501 411.5h27v204h-27z"
          />
          <path
            id="prefix__o_41"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M658.267 516.5h27.235v99h-27.235z"
          />
          <path
            id="prefix__o_40"
            d="M156.5 156.5h59v204h-59v-204z"
            fill="#D6EBFF"
            stroke="#87B6E2"
          />
          <path
            id="prefix__o_39"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M658.5 156.5h27v204h-27z"
          />
          <path
            id="prefix__o_38"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M188.265 411.5H215.5v99h-27.235z"
          />
          <path
            id="prefix__o_37"
            transform="rotate(-90 266.5 614.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M266.5 614.5h27.235v99H266.5z"
          />
          <path
            id="prefix__o_36"
            transform="rotate(-90 266.5 582.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M266.5 582.5h27v204h-27z"
          />
          <path
            id="prefix__o_35"
            transform="rotate(-90 371.5 614.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 614.5h27v204h-27z"
          />
          <path
            id="prefix__o_34"
            transform="rotate(-90 266.5 323.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M266.5 323.5h27.235v99H266.5z"
          />
          <path
            id="prefix__o_33"
            transform="rotate(-90 266.5 291.735)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M266.5 291.735h27.235v99H266.5z"
          />
          <path
            id="prefix__o_32"
            transform="rotate(-90 371.5 291.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 291.5h27v204h-27z"
          />
          <path
            id="prefix__o_31"
            transform="rotate(-90 736.5 291.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 291.5h27v204h-27z"
          />
          <path
            id="prefix__o_30"
            transform="rotate(-90 371.5 323.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 323.5h27.235v99H371.5z"
          />
          <path
            id="prefix__o_29"
            transform="rotate(-90 841.5 323.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M841.5 323.5h27.235v99H841.5z"
          />
          <path
            id="prefix__o_28"
            transform="rotate(-90 371.5 400.735)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 400.735h27.235v204H371.5z"
          />
          <path
            id="prefix__o_27"
            transform="rotate(-90 266.5 506.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M266.5 506.5h27v204h-27z"
          />
          <path
            id="prefix__o_26"
            transform="rotate(-90 371.5 474.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 474.5h27v204h-27z"
          />
          <path
            id="prefix__o_25"
            transform="rotate(-90 476.5 506.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M476.5 506.5h27.235v99H476.5z"
          />
          <path
            id="prefix__o_24"
            transform="rotate(-90 266.5 183.735)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M266.5 183.735h27.235v99H266.5z"
          />
          <path
            id="prefix__o_23"
            transform="rotate(-90 736.5 215.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 215.5h27.235v99H736.5z"
          />
          <path
            id="prefix__o_22"
            transform="rotate(-90 736.5 183.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 183.5h27v204h-27z"
          />
          <path
            id="prefix__o_21"
            transform="rotate(-90 736.5 433.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 433.5h27.235v99H736.5z"
          />
          <path
            id="prefix__o_20"
            transform="rotate(-90 841.5 433.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M841.5 433.5h27.235v99H841.5z"
          />
          <path
            id="prefix__o_19"
            transform="rotate(-90 736.5 511.735)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 511.735h27.235v99H736.5z"
          />
          <path
            id="prefix__o_18"
            transform="rotate(-90 736.5 543.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 543.5h27v49h-27z"
          />
          <path
            id="prefix__o_17"
            transform="rotate(-90 736.5 401.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M736.5 401.5h27v204h-27z"
          />
          <path
            id="prefix__o_16"
            transform="rotate(-90 371.5 215.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 215.5h27.235v99H371.5z"
          />
          <path
            id="prefix__o_15"
            transform="rotate(-90 476.5 215.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M476.5 215.5h27.235v99H476.5z"
          />
          <path
            id="prefix__o_14"
            transform="rotate(-90 371.5 183.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M371.5 183.5h27v204h-27z"
          />
          <path
            id="prefix__o_13"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M626.5 156.5h27.235v99H626.5z"
          />
          <path
            id="prefix__o_12"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M61.5 466.5h10v149h-10z"
          />
          <path
            id="prefix__o_11"
            transform="rotate(-90 312.5 711.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M312.5 711.5h10v442h-10z"
          />
          <path
            id="prefix__o_10"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M61.5 156.5h10v149h-10z"
          />
          <path
            id="prefix__o_9"
            transform="rotate(-90 311.5 71.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M311.5 71.5h10v304h-10z"
          />
          <path
            id="prefix__o_8"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M1040.5 156.5h10v167h-10z"
          />
          <path
            id="prefix__o_7"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M1040.5 329.5h10v149h-10z"
          />
          <path
            id="prefix__o_6"
            transform="rotate(-90 156.5 71.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M156.5 71.5h10v149h-10z"
          />
          <path
            id="prefix__o_5"
            transform="rotate(-90 157.5 711.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M157.5 711.5h10v149h-10z"
          />
          <path
            id="prefix__o_4"
            transform="rotate(-90 621.5 71.5)"
            fill="#D6EBFF"
            stroke="#87B6E2"
            d="M621.5 71.5h10v304h-10z"
          />
          <g id="prefix__o_3">
            <mask id="prefix__path-245-inside-1" fill="#fff">
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M72 61H61v90h11V72h79V61H72z"
              />
            </mask>
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M72 61H61v90h11V72h79V61H72z"
              fill="#D6EBFF"
            />
            <path
              d="M61 61v-1h-1v1h1zm11 0h1v-1h-1v1zm-11 90h-1v1h1v-1zm11 0v1h1v-1h-1zm0-79v-1h-1v1h1zm79 0v1h1v-1h-1zm0-11h1v-1h-1v1zm-79 0h-1v1h1v-1zm-11 1h11v-2H61v2zm1-1h-2 2zm0 11V61h-2v11h2zm0 79V72h-2v79h2zm10-1H61v2h11v-2zm-1-78v79h2V72h-2zm80-1H72v2h79v-2zm-1-10v11h2V61h-2zm-78 1h79v-2H72v2zm-1-1h2-2z"
              fill="#87B6E2"
              mask="url(#prefix__path-245-inside-1)"
            />
          </g>
          <g id="prefix__o_2">
            <mask id="prefix__path-247-inside-2" fill="#fff">
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M1051 72V61H931v11h109v79h11V72z"
              />
            </mask>
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M1051 72V61H931v11h109v79h11V72z"
              fill="#D6EBFF"
            />
            <path
              d="M1051 61h1v-1h-1v1zm0 11v1h1v-1h-1zm0-11v1-1zm-120 0v-1h-1v1h1zm0 11h-1v1h1v-1zm109 0h1v-1h-1v1zm0 79h-1v1h1v-1zm11 0v1h1v-1h-1zm0-79v-1h-1v1h1zm-1-11v11h2V61h-2zm1 1v-2 2zm-11 0h11v-2h-11v2zm-109 0h109v-2H931v2zm1 10V61h-2v11h2zm108-1H931v2h109v-2zm1 80V72h-2v79h2zm10-1h-11v2h11v-2zm-1-78v79h2V72h-2zm1-1v2-2z"
              fill="#87B6E2"
              mask="url(#prefix__path-247-inside-2)"
            />
          </g>
          <g id="prefix__o_1">
            <mask id="prefix__path-249-inside-3" fill="#fff">
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M61 701v11h91v-11H72v-80H61v80z"
              />
            </mask>
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M61 701v11h91v-11H72v-80H61v80z"
              fill="#D6EBFF"
            />
            <path
              d="M61 712h-1v1h1v-1zm0-11h-1 1zm91 11v1h1v-1h-1zm0-11h1v-1h-1v1zm-80 0h-1v1h1v-1zm0-80h1v-1h-1v1zm-11 0v-1h-1v1h1zm1 91v-11h-2v11h2zm-1-1v2-2zm11 0H61v2h11v-2zm80 0H72v2h80v-2zm-1-10v11h2v-11h-2zm-79 1h80v-2H72v2zm-1-81v80h2v-80h-2zm-10 1h11v-2H61v2zm1 79v-80h-2v80h2z"
              fill="#87B6E2"
              mask="url(#prefix__path-249-inside-3)"
            />
          </g>
        </g>
      </g>
      <defs>
        <filter
          id="prefix__filter0_d"
          x={0}
          y={0}
          width={1112.5}
          height={773}
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity={0} result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          />
          <feOffset />
          <feGaussianBlur stdDeviation={25} />
          <feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0" />
          <feBlend in2="BackgroundImageFix" result="effect1_dropShadow" />
          <feBlend in="SourceGraphic" in2="effect1_dropShadow" result="shape" />
        </filter>
      </defs>
    </svg>
  );
}

export default SvgComponent;
